lib_info:
    sg_length: 20
    vector: "N" # Vector sequence to be removed from reads (N for none)
    left_trim : 0 # Trim n bases from 5' end of reads
    species: human
csv: # If no fasta is available, provide a csv file with sgRNA sequences
  name_column: 3 # Column number with gene names
  sequence_column: 2 # Column number with sgRNA sequences
mismatch: 0 # Mismatches allowed during alignment
stats: 
  skip: none # Skip mageck, bagel2, both, or none
  mageck:
    extra_mageck_arguments: "" 
    mageck_control_genes: all # All or file with control genes
    fdr: 0.25 # FDR threshold for mageck plotting
    apply_CNV_correction: False # Apply CNV correction to mageck results
    cell_line: K562_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE # Cell line for CNV correction
resources:
  trim:
    cpu: 4
    time: 60
  fastqc:
    cpu: 4
    time: 60
  count:
    cpu: 8
    time: 120
  stats:
    cpu: 2
    time: 60
