lib_info:
    sg_length: 20
    vector: ""
    left_trim : 0 #trim n bases from 5' end of reads
    species: human
mismatch: 0 #mismatches allowed during alignment
stats: 
  skip: none #skip mageck, bagel2, both, or none
  extra_mageck_arguments: "" 
  mageck_control_genes: all #all or file with control genes
  fdr: 0.25 #FDR threshold for mageck plotting
resources:
  account: XXX
  partition: cclake
  max_jobs: 100
  trim:
    cpu: 4
    time: 60
  fastqc:
    cpu: 4
    time: 60
  count:
    cpu: 8
    time: 120
  stats:
    cpu: 2
    time: 60
