$schema: "http://json-schema.org/draft-06/schema#"

description: Snakemake configuration file

type: object

properties:
  lib_info:
    type: object
    properties:
      sg_length:
        type: integer
        minimum: 12
        maximum: 23
      vector:
        type: string
        pattern: "^[NATGCnatgc]+$"
        description: Vector sequence to be removed from reads (N for none)
      left_trim:
        type: integer
        minimum: 0
      species:
        type: string
        enum: ["human", "mouse"]
    required:
      - sg_length
      - vector
      - left_trim
      - species

  csv:
    type: object
    properties:
      name_column:
        type: integer
        minimum: 1
      sequence_column:
        type: integer
    required:
      - name_column
      - sequence_column

  mismatch:
    type: integer
    minimum: 0
    maximum: 2

  stats:
    type: object
    properties:
      skip:
        description: Skip analysis with MAGeCK/BAGEL2
        type: string
        enum: ["mageck", "bagel2", "both", "none"]
      bagel2:
        type: object
        properties:
          custom_gene_lists:
            type: object
            properties:
              essential_genes:
                type: string
              non_essential_genes:
                type: string
      mageck:
        type: object
        properties:
          extra_mageck_arguments:
            type: string
          mageck_control_genes:
            type: string
          fdr:
            type: number
            minimum: 0
            maximum: 1
          apply_CNV_correction:
            type: boolean
          cell_line:
            type: string
      pathway_analysis:
        type: object
        properties:
          run:
            type: boolean
          data:
            type: string
            enum: ["enriched", "depleted", "both"]
          dbs:
            type: array
            items:
              type: string
          terms:
            type: integer
            minimum: 1
          top_genes:
            type: integer
            minimum: 0
            
    required:
    - skip
    - mageck
    - pathway_analysis
  
  resources:
    type: object
    properties:
      trim:
        type: object
        properties:
          cpu:
            type: integer
            minimum: 1
          time:
            type: integer
      fastqc:
        type: object
        properties:
          cpu:
            type: integer
            minimum: 1
          time:
            type: integer
      count:
        type: object
        properties:
          cpu:
            type: integer
            minimum: 1
          time:
            type: integer
      stats:
        type: object
        properties:
          cpu:
            type: integer
            minimum: 1
          time:
            type: integer

required:
  - lib_info
  - mismatch
  - stats
  - resources