$schema: "http://json-schema.org/draft-06/schema#"

description: Snakemake configuration file

type: object

properties:
  lib_info:
    type: object
    properties:
      library_file:
        type: string
      left_trim:
        type: integer
      vector:
        type: string
      sg_length:
        type: integer
      species:
        type: string

  csv:
    type: object
    properties:
      name_column:
        type: integer
      gene_column:
        type: integer
      sequence_column:
        type: integer

  mismatch:
    type: integer
    minimum: 0
    maximum: 2

  stats:
    type: object
    properties:
      crisprcleanr:
        type: object
        properties:
          library_name:
            type: string

      bagel2:
        type: object
        properties:
          run:
            type: boolean
          custom_gene_lists:
            type: object
            properties:
              essential_genes:
                type: string
              non_essential_genes:
                type: string

      mageck:
        type: object
        properties:
          run:
            type: boolean
          apply_crisprcleanr:
            type: boolean
          extra_mageck_arguments:
            type: string
          mageck_control_genes:
            type: string
          apply_CNV_correction:
            type: boolean
          cell_line:
            type: string

      drugz:
        type: object
        properties:
          run:
            type: boolean
          apply_crisprcleanr:
            type: boolean
          extra:
            type: string

      pathway_analysis:
        type: object
        properties:
          run:
            type: boolean
          data:
            type: string
          fdr:
            type: number
          top_genes:
            type: integer